### ISSUE TITLE
Rename builder-x to x needed

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/devops-agent#2]
In fact, what devops needs is a runtime, not a builder.  Builder is confusing, and it is regarded as images of S2i.

We need to make the following adjustments：

- docs，https://github.com/kubesphere/docs.kubesphere.io
- installer，https://github.com/kubesphere/ks-installer

**Comment by LinuxSuRen** [comment]
Actually, they should be a build environment instead of a runtime. For example, in order to compile the Java source, we need JDK instead of JRE. We don't run some kind of application in these agents. According to this, I think the naming of `builder` is fine.

Please explain more if you still believe we need to make changes.

**Comment by shaowenchen** [comment]
It is a builder in CI, but runtime in CD. Builder or Runtime can't appear the feature.
The main reason is that users are confused with the s2i builder.
